replicaCount: 1

image:
  repository: vladysamigos/kugify
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000
  nodePort: 30080 

resources: {}

ingress:
  enabled: false

envFromSecret: kugify-secrets
