name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: vladysamigos/kugify

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install uv
        run: pip install uv

      - name: Install dev dependencies
        run: make install

      - name: Ruff lint check
        run: make check-lint

      - name: isort check
        run: make check-sort

      - name: Black format check
        run: make check-format

      - name: Run pytest
        run: make test

      # - name: Helm lint
      #   run: helm lint charts/kugify

      - name: Helm template
        run: helm template kugify charts/kugify --values charts/kugify/values.yaml

  build:
    runs-on: ubuntu-latest
    needs: check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv and project dependencies
        run: |
          pip install uv
          uv pip install --system .[dev]

      - name: Run code checks
        run: |
          make check-format
          make check-sort
          make check-lint
          make test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Extract short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Deploy with Helm
        run: |
          helm upgrade --install kugify charts/kugify \
            --namespace kugify \
            --create-namespace \
            --set image.repository=vladysamigos/kugify \
            --set image.tag=${{ steps.vars.outputs.sha_short }}
